docservice.mime.edit=application/vnd.openxmlformats-officedocument.wordprocessingml.document|\
                     application/vnd.openxmlformats-officedocument.spreadsheetml.sheet|\
                     application/vnd.openxmlformats-officedocument.presentationml.presentation
